fullnameOverride: calico

serviceAccount:
  create: true

calico:
  tag: v3.8.1
  typha:
    image: quay.io/calico/typha
  node:
    image: quay.io/calico/node

autoscaler:
  tag: "1.1.2"
  image: k8s.gcr.io/cluster-proportional-autoscaler-amd64
