apiVersion: v1
kind: Service
metadata:
  name: {{ template "appmesh-inject.fullname" . }}
  labels:
{{ include "appmesh-inject.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: {{ include "appmesh-inject.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
