{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "aws-node-termination-handler.serviceAccountName" . }}
  labels:
{{ include "aws-node-termination-handler.labels" . | indent 4 }}
{{- end -}}
